apiVersion: v1
items:
- apiVersion: v1
  data:
    password: bWFyY2FkbWlu
    url: aHR0cHM6Ly8xMC4wLjAuMTEz
    username: YWRtaW4=
  kind: Secret
  metadata:
    name: bigip-credentials
    namespace: kube-system
    resourceVersion: "428661"
    selfLink: /api/v1/namespaces/kube-system/secrets/bigip-credentials
  type: Opaque
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""