apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: f5-k8s-controller
    namespace: kube-system
spec:
    replicas: 1
    template:
        metadata:
            name: f5-k8s-controller
            labels:
                app: f5-k8s-controller
        spec:
            containers:
                - 
                    name: f5-k8s-controller
                    image: 'localhost:5000/cc'
                    env:
                        - 
                            name: BIGIP_USERNAME
                            valueFrom:
                                secretKeyRef:
                                    name: bigip-credentials
                                    key: username
                        - 
                            name: BIGIP_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: bigip-credentials
                                    key: password
                        - 
                            name: BIGIP_URL
                            valueFrom:
                                secretKeyRef:
                                    name: bigip-credentials
                                    key: url
                    command:
                        - /app/bin/k8s-bigip-ctlr
                    args:
                        - '--bigip-url=$(BIGIP_URL)'
                        - '--bigip-username=$(BIGIP_USERNAME)'
                        - '--bigip-password=$(BIGIP_PASSWORD)'
                        - '--namespace=default'
                        - '--bigip-partition=kubernetes'
                        - '--pool-member-type=cluster'